# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-17 05:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('logo', models.ImageField(upload_to='logos', verbose_name='Logo')),
                ('telefono', models.CharField(max_length=15, verbose_name='Telefono')),
                ('inicio', models.DateField(blank=True, null=True, verbose_name='Inicio')),
                ('fin', models.DateField(blank=True, null=True, verbose_name='Fin')),
                ('correo', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo')),
                ('direccion', models.TextField(verbose_name='Direccion')),
                ('estado', models.BooleanField(default=False, verbose_name='Estado')),
                ('coordinador', models.CharField(max_length=50, verbose_name='Coordinador')),
                ('departamento', models.CharField(max_length=100)),
                ('responsable', models.CharField(max_length=100)),
                ('carreras', models.ManyToManyField(related_name='empresas', to='registros.Carrera')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
