# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-18 21:30
from __future__ import unicode_literals

import apps.modulos.validators
import apps.practicas.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registros', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos', verbose_name='Logo')),
                ('telefono', models.CharField(max_length=15, verbose_name='Telefono')),
                ('inicio', models.DateField(verbose_name='Inicio del Convenio')),
                ('fin', models.DateField(verbose_name='Finalizacion del Convenio')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo')),
                ('direccion', models.TextField(verbose_name='Direccion')),
                ('estado', models.BooleanField(default=False, verbose_name='Estado')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('gerente', models.CharField(max_length=100, verbose_name='Nombre del Gerente')),
                ('descripcion', models.TextField(verbose_name='Descricion')),
                ('carreras', models.ManyToManyField(related_name='empresas', to='registros.Carrera')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('view_empresa', 'Puede acceder a Empresa')],
            },
        ),
        migrations.CreateModel(
            name='Informe_practicas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('convenio', models.FileField(upload_to='informes_practicas', validators=[apps.modulos.validators.valid_extension])),
            ],
            options={
                'permissions': [('view_informe_practicas', 'Puede acceder a Informe Practicas')],
            },
        ),
        migrations.CreateModel(
            name='Registro_practicas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presentacion', models.DateField(verbose_name='Fecha de Presentacion')),
                ('fin', models.DateField(blank=True, null=True, verbose_name='Fecha de finalizaci\xf3n')),
                ('horas', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Horas comletadas')),
                ('calificacion', models.FloatField(blank=True, default=0, null=True, verbose_name='Calificaci\xf3n del Estudiante')),
                ('solicitud', models.ImageField(upload_to=apps.practicas.models.generate_path, verbose_name='Evidencia de Solicitud')),
                ('aceptacion', models.ImageField(upload_to=apps.practicas.models.generate_path, verbose_name='Evidencia de Aceptaci\xf3n')),
                ('evaluacion', models.ImageField(blank=True, null=True, upload_to=apps.practicas.models.generate_path, verbose_name='Fecha de Evaluaci\xf3n')),
                ('culminacion', models.ImageField(blank=True, null=True, upload_to=apps.practicas.models.generate_path, verbose_name='Fecha de Culminaci\xf3n')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado del registro')),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practicas', to='registros.Carrera')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practicas', to='practicas.Empresa')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practicas', to='registros.Estudiante')),
            ],
            options={
                'permissions': (('view_registro', 'Puede visualizar el registro'),),
            },
        ),
    ]
