# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-28 15:55
from __future__ import unicode_literals

import apps.modulos.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practicas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informe_practicas',
            name='convenio',
            field=models.FileField(upload_to='informes_practicas', validators=[apps.modulos.validators.valid_extension_docx]),
        ),
    ]
