# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-18 15:15
from __future__ import unicode_literals

import apps.practicas.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0001_initial'),
        ('practicas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presentacion', models.DateField(verbose_name='Fecha de Presentacion')),
                ('fin', models.DateField(blank=True, null=True, verbose_name='Fecha de finalizaci\xf3n')),
                ('horas', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Horas comletadas')),
                ('calificacion', models.FloatField(blank=True, default=0, null=True, verbose_name='Calificaci\xf3n del Estudiante')),
                ('solicitud', models.ImageField(upload_to=apps.practicas.models.generate_path, verbose_name='Fecha de Solicitud')),
                ('aceptacion', models.ImageField(upload_to=apps.practicas.models.generate_path, verbose_name='Fecha de Aceptaci\xf3n')),
                ('evaluacion', models.ImageField(blank=True, null=True, upload_to=apps.practicas.models.generate_path, verbose_name='Fecha de Evaluaci\xf3n')),
                ('culminacion', models.ImageField(blank=True, null=True, upload_to=apps.practicas.models.generate_path, verbose_name='Fecha de Culminaci\xf3n')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado del registro')),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practicas', to='registros.Carrera')),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practicas', to='practicas.Empresa')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practicas', to='registros.Estudiante')),
            ],
            options={
                'permissions': (('view_regstro', 'Puede visualizar el registro'),),
            },
        ),
    ]
