# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-05 01:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practicas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='fin',
            field=models.DateField(null=True, verbose_name='Finalizacion del Convenio'),
        ),
    ]
