# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-18 21:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practicas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registro_practicas',
            options={'permissions': (('view_registro_practicas', 'Puede visualizar el registro'),)},
        ),
    ]
