# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-18 15:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practicas', '0002_registro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registro',
            old_name='entidad',
            new_name='empresa',
        ),
    ]
