# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-09 03:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practicas', '0003_auto_20190104_2134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='descripcion',
        ),
    ]
