# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-18 16:09
from __future__ import unicode_literals

import apps.practicas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practicas', '0003_auto_20180918_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='aceptacion',
            field=models.ImageField(upload_to=apps.practicas.models.generate_path, verbose_name='Evidencia de Aceptaci\xf3n'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='solicitud',
            field=models.ImageField(upload_to=apps.practicas.models.generate_path, verbose_name='Evidencia de Solicitud'),
        ),
    ]
