# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-01 06:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docente',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='docente',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
