# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-17 05:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfil',
            options={'permissions': (('admin_vinc', 'Administrador de Vinculacion'), ('admin_prac', 'Administrador de Practicas'), ('resp_vinc', 'Responsable de Vinculacion'), ('resp_prac', 'Responsable de Practicas'))},
        ),
    ]
