# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-17 08:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0002_auto_20180917_0042'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Docentes',
            new_name='Docente',
        ),
    ]
